export const ADD_TO_FAVORITE_LIST = 'ADD_TO_FAVORITE_LIST';
export const REMOVE_FROM_FAVORITE_LIST = 'REMOVE_FROM_FAVORITE_LIST';
export const LOAD_FAVORITE_LIST_FROM_LOCAL_STORAGE =
  'LOAD_FAVORITE_LIST_FROM_LOCAL_STORAGE';
